import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import localFont from "next/font/local";

const geist = localFont({
  src: "../public/fonts/Geist.ttf",
});
const geistMono = localFont({
  src: "../public/fonts/GeistMono.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geist.className} ${geistMono.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
